const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const IGNORE = /gstatic|firebase|firestore|cloud|net::|Failed to load|ERR_|favicon|CONNECT|installations|BloomFilter|Fetch API|Access-Control|CORS|the server responded|400 \(|403 \(|wa\.me|telegram|anon auth/i;
(async () => {
  const browser = await chromium.launch();
  const page = await (await browser.newContext({ viewport:{width:400,height:900} })).newPage();
  const errors=[]; page.on('console',m=>{ if(m.type()==='error'&&!IGNORE.test(m.text())) errors.push('C:'+m.text()); });
  page.on('pageerror',e=>{ if(!IGNORE.test(e.message)) errors.push('P:'+e.message); });
  page.on('dialog', d=>d.accept());
  const log=(...a)=>console.log(...a);
  await page.goto('http://localhost:8123/index.html',{waitUntil:'load'}); await page.waitForTimeout(1200);
  await page.fill('#lockName','مالك'); await page.fill('#lockInput','0707'); await page.click('#lockEnter'); await page.waitForTimeout(400);
  await page.evaluate(()=>{ const d=iso(new Date()); window._opened=[]; window.open=(u)=>{ window._opened.push(u); return null; };
    state.storeCustomers=[{id:'c1',name:'أهل دار أنفع',phone:'22540775',country:'222',editedAt:d}];
    state.carOps=[{id:'a1',no:'A1',vehicle:'سيارة',wash:'غسيل',price:500,phone:'22540775',country:'222',paid:false,date:d,editedAt:d},{id:'a2',no:'A2',vehicle:'شاحنة',wash:'غسيل',price:1000,phone:'30156145',country:'222',paid:false,date:d,editedAt:d}];
    state.carpetOrders=[{id:'k1',no:'K1',customer:'أهل دار أنفع',phone:'22540775',country:'222',type:'سجادة',count:1,unit:700,price:700,status:'ready',paid:false,date:d,editedAt:d}];
    state.laundryOrders=[{id:'l1',no:'L1',customer:'أهل دار أنفع',phone:'22540775',country:'222',type:'قميص',service:'كي',count:1,unit:2000,price:2000,status:'wash',paid:false,date:d,editedAt:d}];
    state.storeSales=[{id:'s1',no:'S1',customerId:'c1',customerName:'أهل دار أنفع',items:[],total:300,paidAmount:0,paid:false,date:d,editedAt:d}];
    state.suppliers=[]; state.storePurchases=[]; state.debtKind='all'; save(); render(); });
  const d = await page.evaluate(()=>debtors().map(x=>({n:x.name,t:x.total,by:x.by})));
  const a=d.find(x=>x.n==='أهل دار أنفع');
  log('per-kind totals (car 500, rug 700, lnd 2000, store 300): '+(!!a&&a.by.car===500&&a.by.rug===700&&a.by.lnd===2000&&a.by.store===300&&a.t===3500)+' (expect true)');
  await page.click('[data-tab="contacts"]'); await page.click('[data-csub="debts"]'); await page.waitForTimeout(250);
  log('section buttons shown with totals: '+((await page.$$('[data-debtkind]')).length===5&&/🚗 السيارات/.test(await page.textContent('.debt-kinds')))+' (expect true)');
  let txt=await page.textContent('main');
  log('"all" view shows per-section breakdown on card: '+(/السيارات: 500/.test(txt)&&/الملابس: 2,000/.test(txt))+' (expect true)');
  await page.click('[data-debtkind="car"]'); await page.waitForTimeout(250); txt=await page.textContent('main');
  log('cars section: total 1,500 and 2 debtors: '+(/1,500/.test(txt)&&/\(2 مدين\)/.test(txt))+' (expect true)');
  log('card shows only car amount: '+(/500 أوقية/.test(txt)&&!/3,500/.test(txt))+' (expect true)');
  await page.click('[data-debt-wa="c:c1"]'); await page.waitForTimeout(150);
  const msg=decodeURIComponent((await page.evaluate(()=>window._opened.pop()||'')).split('text=')[1]||'');
  log('reminder uses section amount (500) not total: '+(msg.includes('500')&&!msg.includes('3,500'))+' (expect true)');
  await page.click('[data-debtkind="lnd"]'); await page.waitForTimeout(250); txt=await page.textContent('main');
  log('laundry section: 2,000 (1 مدين): '+(/2,000/.test(txt)&&/\(1 مدين\)/.test(txt))+' (expect true)');
  await page.click('[data-debtkind="rug"]'); await page.waitForTimeout(250);
  log('carpet section 700: '+/700/.test(await page.textContent('.debt-stat'))+' (expect true)');
  await page.click('[data-debtkind="store"]'); await page.waitForTimeout(250); txt=await page.textContent('main');
  log('store section 300 + collect button: '+(/300/.test(txt)&&(await page.isVisible('[data-dc-pay]')))+' (expect true)');
  // store tab shows store only (no switcher)
  await page.click('[data-tab="store"]'); await page.click('[data-ssub="debts"]'); await page.waitForTimeout(250);
  log('store debts tab has no section switcher and shows 300: '+((await page.$$('[data-debtkind]')).length===0&&/300/.test(await page.textContent('main')))+' (expect true)');
  await page.click('[data-tab="contacts"]'); await page.click('[data-csub="debts"]'); await page.waitForTimeout(250);
  await page.click('[data-debtkind="all"]'); await page.waitForTimeout(200);
  log('back to all: 4,500 (incl. truck): '+/4,500/.test(await page.textContent('.debt-stat'))+' (expect true)');
  log('bot debts reply split by section: '+(await page.evaluate(()=>/🚗 السيارات: 1,500/.test(tgHandleText('📌 الديون'))&&/👕 الملابس: 2,000/.test(tgHandleText('📌 الديون'))))+' (expect true)');
  log('filter not synced: '+(await page.evaluate(()=>!('debtKind' in cloudCopy())))+' (expect true)');
  log('\nERRORS:', errors.length?errors.join('\n'):'NONE ✅');
  await browser.close();
})().catch(e=>{console.error('CRASH',e);process.exit(1);});
